import { Sequelize } from 'sequelize';
declare let sequelize: Sequelize;
declare const Campaign: typeof import("./campaigns").Campaign;
declare const InInstantwinPrize: typeof import("./in_instantwin_prizes").InInstantwinPrize;
declare const InInstantwinTemplate: typeof import("./in_instantwin_templates").InInstantwinTemplate;
declare const InInstantwinNode: typeof import("./in_instantwin_nodes").InInstantwinNode;
declare const InInstantwinEdge: typeof import("./in_instantwin_edges").InInstantwinEdge;
declare const InInstantwinMessage: typeof import("./in_instantwin_messages").InInstantwinMessage;
declare const InInstantwinMessageSelectOption: typeof import("./in_instantwin_message_select_options").InInstantwinMessageSelectOption;
declare const InInstantwinMessageCard: typeof import("./in_instantwin_message_cards").InInstantwinMessageCard;
declare const InInstantwinMessageCardButton: typeof import("./in_instantwin_message_card_buttons").InInstantwinMessageCardButton;
declare const InInstantwinConversation: typeof import("./in_instantwin_conversations").InInstantwinConversation;
declare const InInstantwinMessageLottery: typeof import("./in_instantwin_message_lottery").InInstantwinMessageLottery;
declare const db: {
    sequelize: Sequelize;
    Sequelize: typeof Sequelize;
    Campaign: typeof import("./campaigns").Campaign;
    InInstantwinPrize: typeof import("./in_instantwin_prizes").InInstantwinPrize;
    InInstantwinTemplate: typeof import("./in_instantwin_templates").InInstantwinTemplate;
    InInstantwinNode: typeof import("./in_instantwin_nodes").InInstantwinNode;
    InInstantwinEdge: typeof import("./in_instantwin_edges").InInstantwinEdge;
    InInstantwinMessage: typeof import("./in_instantwin_messages").InInstantwinMessage;
    InInstantwinMessageSelectOption: typeof import("./in_instantwin_message_select_options").InInstantwinMessageSelectOption;
    InInstantwinMessageCard: typeof import("./in_instantwin_message_cards").InInstantwinMessageCard;
    InInstantwinMessageCardButton: typeof import("./in_instantwin_message_card_buttons").InInstantwinMessageCardButton;
    InInstantwinConversation: typeof import("./in_instantwin_conversations").InInstantwinConversation;
    InInstantwinMessageLottery: typeof import("./in_instantwin_message_lottery").InInstantwinMessageLottery;
};
export default db;
export { sequelize, Campaign, InInstantwinPrize, InInstantwinTemplate, InInstantwinNode, InInstantwinEdge, InInstantwinMessage, InInstantwinMessageSelectOption, InInstantwinMessageCard, InInstantwinMessageCardButton, InInstantwinConversation, InInstantwinMessageLottery, };
