// Select option API constants
export const SELECT_OPTION_CONSTANTS = {
  // Validation limits
  MAX_TEXT_LENGTH: 200,
  MAX_VALUE_LENGTH: 100,
  MAX_STEP_ORDER: 999,

  // Pagination defaults
  DEFAULT_PAGE_SIZE: 10,
  MAX_PAGE_SIZE: 100,
  MIN_PAGE_SIZE: 1,

  // Error codes
  ERROR_CODES: {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    SELECT_OPTION_NOT_FOUND: 'SELECT_OPTION_NOT_FOUND',
    MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
    DUPLICATE_STEP_ORDER: 'DUPLICATE_STEP_ORDER',
    DUPLICATE_VALUE: 'DUPLICATE_VALUE',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  },

  // Success messages
  MESSAGES: {
    SELECT_OPTION_CREATED: '選択肢が正常に作成されました',
    SELECT_OPTION_UPDATED: '選択肢が正常に更新されました',
    SELECT_OPTION_DELETED: '選択肢が正常に削除されました',
    SELECT_OPTIONS_RETRIEVED: '選択肢一覧を取得しました',
    SELECT_OPTION_RETRIEVED: '選択肢詳細を取得しました',
  },
};