// Lottery API constants
export const LOTTERY_CONSTANTS = {
  // Validation limits
  MAX_USER_ID_LENGTH: 100,
  MAX_CUSTOM_WEIGHTS: 50,

  // Lottery limits
  MAX_DAILY_WINS_GLOBAL: 10,
  MAX_HOURLY_ATTEMPTS: 5,
  MIN_LOTTERY_INTERVAL_MINUTES: 5,

  // Error codes
  ERROR_CODES: {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    LOTTERY_NOT_ELIGIBLE: 'LOTTERY_NOT_ELIGIBLE',
    CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
    TEMPLATE_NOT_FOUND: 'TEMPLATE_NOT_FOUND',
    NO_PRIZES_AVAILABLE: 'NO_PRIZES_AVAILABLE',
    LOTTERY_EXECUTION_FAILED: 'LOTTERY_EXECUTION_FAILED',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  },

  // Success messages
  MESSAGES: {
    LOTTERY_EXECUTED: '抽選が実行されました',
    LOTTERY_VALIDATION_COMPLETED: '抽選資格確認が完了しました',
    LOTTERY_WIN: 'おめでとうございます！当選しました！',
    LOTTERY_LOSS: '残念！今回は当選しませんでした。',
  },
};